import os
import subprocess
import shutil
from pathlib import Path

# --- CONFIGURATION ---
SRC_DIR = Path("src")
DIST_DIR = Path("docs")
PANDOC_ARGS = ["--wrap=preserve"]

# Types of files we want Git to track in the docs folder
ALLOWED_EXTENSIONS = {".md", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".pdf"}

def ensure_gitignore():
    """Creates a protective .gitignore inside the docs directory."""
    gitignore_path = DIST_DIR / ".gitignore"
    content = (
        "# Automatically generated by publish.py\n"
        "*\n"                # Ignore everything
        "!.gitignore\n"      # Except this file
        "!*/\n"              # Except directories (to allow traversal)
    )
    for ext in ALLOWED_EXTENSIONS:
        content += f"!*{ext}\n" # Except our allowed file types
    
    with open(gitignore_path, "w") as f:
        f.write(content)
    print(f"  🛡️  Created/Updated {gitignore_path}")

def build_project():
    print(f"🚀 Starting build: {SRC_DIR} -> {DIST_DIR}")
    
    # 1. Prepare the docs directory
    if DIST_DIR.exists():
        for item in DIST_DIR.iterdir():
            if item.name in [".git", ".gitignore"]:
                continue
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
    else:
        DIST_DIR.mkdir(parents=True, exist_ok=True)

    # 2. Ensure .gitignore exists before adding files
    ensure_gitignore()

    # 3. Walk through the source directory
    for src_path in SRC_DIR.rglob("*"):
        relative_path = src_path.relative_to(SRC_DIR)
        dist_path = DIST_DIR / relative_path

        if src_path.is_dir():
            dist_path.mkdir(parents=True, exist_ok=True)
            continue

        # Convert Markdown
        if src_path.suffix.lower() == ".md":
            convert_markdown(src_path, dist_path)
        # Copy allowed assets
        elif src_path.suffix.lower() in ALLOWED_EXTENSIONS:
            shutil.copy2(src_path, dist_path)
            print(f"  📁 Copied: {relative_path}")

def convert_markdown(src_file, dist_file):
    try:
        command = [
            "pandoc", str(src_file),
            "-f", "markdown",
            "-t", "gfm",
            "-o", str(dist_file)
        ] + PANDOC_ARGS
        subprocess.run(command, check=True)
        print(f"  📄 Converted: {src_file.name}")
    except Exception as e:
        print(f"  ❌ Error converting {src_file}: {e}")

if __name__ == "__main__":
    build_project()
    print("\n✅ Build complete! Folder 'docs/' is ready for GitHub.")